Image::rotate90(int32 n),rotated90(int32 n),の追加
Siv3D/OpenSiv3D pull request #1090
Opened 2023-09-16 11:32 UTC by comefrombottom

2023-09-16 15:43 UTC, Reputeless requested changes
コメント 3 箇所に対応する追加のコミットをしてください。

2023-09-16 15:43 UTC, Reputeless commented on Siv3D/src/Siv3D/Image/SivImage.cpp
> +		}
この式は `n == -4` のとき 4 を返して「予期していない分岐」に入ります。
コードを読んだ誰かが `default:` を無意味だと思って削ると不正になるので修正が必要です。

パターンが限定されるので、次のように取りうる値を `case` で網羅するのが、読者にやさしく間違いにくいと思います。

```cpp
	switch (n % 4) // 時計回りに何回 90° 回転するか
	{
	case 1:
	case -3:
		return 90 ...; // 1 回または -3 回
	case 2:
	case -2:
		return 180 ...; // 2 回または -2 回
	case 3:
	case -1:
		return 270 ...; // 3 回または -1 回
	default:
		return 0 ...; // 0 回
	}
```

2023-09-16 15:43 UTC, Reputeless commented on Siv3D/src/Siv3D/Image/SivImage.cpp
> +		}
要修正

2023-09-16 15:43 UTC, Reputeless commented on Siv3D/include/Siv3D/Image.hpp
> +		/// @return *this
- @brief 画像を時計回りに 90° * n だけ回転させます。
- @param n 時計回りに 90° 回転させる回数（負の場合は反時計回り）

がより自然なコメントだと思います。

2023-09-17 02:35 UTC, Raclamusi requested changes

2023-09-17 02:35 UTC, Raclamusi commented on Siv3D/src/Siv3D/Image/SivImage.cpp
> +		return rotated90(n);
```suggestion
		switch (n % 4) // 時計回りに何回 90° 回転するか
		{
		case 1:
		case -3:
			return std::move(*this).rotated90(); // 1 回または -3 回
		case 2:
		case -2:
			return std::move(*this).rotated180(); // 2 回または -2 回
		case 3:
		case -1:
			return std::move(*this).rotated270(); // 3 回または -1 回
		default:
			return std::move(*this); // 0 回
		}
```

`Image::rotated90() &&` では、 `Image::rotate90()` が最適化されておらず `Image::rotated90() const&` のほうが高速であるため `Image::rotated90() const&` に委譲する実装にしてありますが、`Image::rotated180() &&` についてはそうではありません。
また、この実装では0回回転する場合にも不要なコピーが発生してしまいます。

ここは、`Image::rotated90(int32) const&` に委譲するのではなく、回転0回のときは自身をムーブし、それ以外のときはそれぞれの `Image::rotated●●() &&` を呼び出すように実装するほうが良いです。

2023-09-17 08:40 UTC, Reputeless approved these changes

2023-09-17 13:25 UTC, merged

2023-09-17 13:27 UTC, Reputeless commented
Merged. Great work!

レビューありがとうございます @Raclamusi 

---
@comefrombottom 

#### ◆ 初めて Siv3D にコミットした方へのご案内
コミッタの方の名前を [AUTHORS](https://github.com/Siv3D/OpenSiv3D/blob/v6_develop/AUTHORS) に記載します。  
表示する名前をお知らせください。特に希望が無い場合は GitHub プロフィールの ID が使われます。

#### ◆ Organization への招待について
OpenSiv3D 本体および Siv3D ドキュメントのリポジトリにコミットをした方、その他顕著な貢献をされた方には、GitHub の [Siv3D Organization メンバー](https://github.com/orgs/Siv3D/people) への招待が送られます。  
招待を受諾し、上記ページで自身のメンバー参加表示設定を「Public」に変更すると、GitHub の自身のプロフィールページに Siv3D のアイコンが表示されます。「Private」のままだと、自身と他のメンバーにしかアイコンは表示されません。