fix JSON
Siv3D/OpenSiv3D pull request #1165
Opened 2023-12-12 11:30 UTC by Reputeless

- コピーコンストラクタ・ムーブコンストラクタの問題を修正 #1117
- `swap` を定義
- Invalid な JSON への代入を有効に
- `JSON::operator =(const std::initializer_list<std::pair<String, JSON>>& list)` が古い内容を消去していなかったバグを修正
- `JSON::operator =(const Array<JSON>& array)` が古い内容を消去していなかったバグを修正

2023-12-28 15:17 UTC, Raclamusi commented on Siv3D/src/Siv3D/JSON/SivJSON.cpp
> +		m_detail = std::exchange(other.m_detail, std::make_shared<detail::JSONDetail>());
```suggestion
		*m_detail = std::exchange(*other.m_detail, detail::JSONDetail{});
```

中身の exchange でいいと思います。

2023-12-28 16:46 UTC, tomolatoon requested changes
## 1. 寿命について
以前触れたように、寿命を延長出来るようにして、次のコードが通るようにするのがいいと思います。
https://discord.com/channels/443310697397354506/999983621408567326/1162390851624898581

```cpp
#include <Siv3D.hpp>

JSON f() {
	JSON json = UR"({
		"foo": 42,
		"bar": "Hello, world!",
		"baz": [1, 2, 3]
	})"_json;

	// operator[] の返り値はプロキシとして働く、pvalue の JSON なので、nlohmann::json の値を所有していない
	return json[U"baz"];
}

void Main() {
	// 現状: 返り値は元のインスタンスが所有している nlohmann::json を参照しているが、その nlohmann::json は既に破棄されているので実行時エラー
	Console << f();
}
```

## 2. メンバ関数`clear`について
`clear`についても、`not m_isValid`のチェックを無くし、invalid な状態からの復帰が出来るようにするべきです。

2023-12-28 16:47 UTC, tomolatoon commented on Siv3D/src/Siv3D/JSON/SivJSON.cpp
> +		m_isValid = std::exchange(other.m_isValid, false);
```cpp
// ムーブ構築なら
auto L = std::move(R);

// ムーブ代入なら
L = std::move(R);
```
としたときに、`R`は新しく構築した`JSONDetail`を渡されるのだから、`m_isValid`は`true`に設定して、swap 戦略のように振る舞うのでいい気がします。

2023-12-28 16:48 UTC, tomolatoon commented on Siv3D/src/Siv3D/JSON/SivJSON.cpp
> +		, m_isValid{ std::exchange(other.m_isValid, false) } {}
`operator =(JSON&&)`と同様の理由で、`false`ではなく、`true`でいいと思います。

2023-12-29 07:30 UTC, Raclamusi commented
> ## 1. 寿命について
> 以前触れたように、寿命を延長出来るようにして、次のコードが通るようにするのがいいと思います。 https://discord.com/channels/443310697397354506/999983621408567326/1162390851624898581

寿命の延長を実装するなら、`detail::JSONDetail::RefType` を `std::shared_ptr<detail::JSONDetail::ValueType>` にするのがよさそうですね。

https://gist.github.com/Raclamusi/08fbf4e70d0f1ac418793b7cdce30f7e/revisions#diff-018619d34dd37983bbc72f3e0cdfbd1a131c0670de6bec1d6bf04bddd206dece

2023-12-29 23:39 UTC, Reputeless commented
ありがとうございます。`JSON` クラス、v0.6.15 以降で根本的に作り直したいので、寿命の延長関連は新規のほうで検討しましょう。そちらは別の Issue を立てます。

2023-12-30 00:06 UTC, Reputeless commented
メンバ関数 `clear` について → `JSON` の `.clear()` は少し特殊で、クリア後も `JSONValueType` を保持する仕様になっています。例えば配列を `.clear()` したら空の配列になるなど。

そのため、Invalid の `.clear()` 結果が Invalid であるのも不自然ではないと考えています。
#1175 ではそもそも Invalid を廃止することも検討しているので、ここら辺の仕様変更はスキップしたいと思います。

2023-12-30 00:16 UTC, Reputeless commented on Siv3D/include/Siv3D/JSON.hpp
> +		JSON(JSON&& other) noexcept;
ムーブコンストラクタは noexcept が良いのですが、現状の仕様上そうせざるを得ないですね。修正します。

2023-12-30 00:24 UTC, Reputeless commented on Siv3D/src/Siv3D/JSON/SivJSON.cpp
> +		m_isValid = std::exchange(other.m_isValid, false);
そうします。

2023-12-30 00:24 UTC, Reputeless commented on Siv3D/src/Siv3D/JSON/SivJSON.cpp
> +		, m_isValid{ std::exchange(other.m_isValid, false) } {}
こちらもそうします。

2023-12-30 00:29 UTC, Reputeless commented
レビューありがとうございました。 @Raclamusi @tomolatoon 
気になった点は修正したので、これでマージする予定です。#1175 についても参加いただけると幸いです。

2023-12-30 01:33 UTC, Raclamusi approved these changes

2023-12-30 04:09 UTC, tomolatoon approved these changes

2023-12-31 02:41 UTC, merged