MultiPolygonにarea()とperimeter()を追加(#1185)
Siv3D/OpenSiv3D pull request #1187
Opened 2024-01-17 16:06 UTC by Ogame3334

MultiPolygonにnoexceptなconstメンバ変数であるarea()とperimeter()を実装

2024-01-17 17:01 UTC, Reputeless requested changes
2 箇所の修正をお願いします。

2024-01-18 01:44 UTC, Ogame3334 commented
フィードバックありがとうございます！
他の実装(`MultiPolygon& MultiPolygon::scaleAt(const Vec2 pos, const Vec2 s)`など)を参考にし、そちらでは*thisを用いていたのでそちらにしたのですが、他の部分の実装とどう異なるのでしょうか？

2024-01-18 02:03 UTC, Reputeless commented
ご指摘のとおりです。他の箇所も `m_data` を使うよう修正すべきです。
他の箇所を修正するコミットを、本件の完了後に別途、あるいは今回の pull-request に含めてもらえると大きな貢献になります。

2024-01-18 02:19 UTC, Reputeless approved these changes

2024-01-18 03:10 UTC, merged

2024-01-18 03:11 UTC, Reputeless commented
Merged. Thanks!

---

#### ◆ 初めて Siv3D にコミットした方へのご案内
コミッタの方の名前を [AUTHORS](https://github.com/Siv3D/OpenSiv3D/blob/v6_develop/AUTHORS) に記載します。  
表示する名前をお知らせください。特に希望が無い場合は GitHub プロフィールの ID が使われます。

#### ◆ Organization への招待について
OpenSiv3D 本体および Siv3D ドキュメントのリポジトリにコミットをした方、その他顕著な貢献をされた方には、GitHub の [Siv3D Organization メンバー](https://github.com/orgs/Siv3D/people) への招待が送られます。  
招待を受諾し、上記ページで自身のメンバー参加表示設定を「Public」に変更すると、GitHub の自身のプロフィールページに Siv3D のアイコンが表示されます。「Private」のままだと、自身と他のメンバーにしかアイコンは表示されません。

2024-01-18 04:01 UTC, Ogame3334 commented
ありがとうございます！
表示する名前は「緑獺おがめ」でお願いします！