2D 物理演算で三角形・四角形・ポリゴン・線分などの形状のセンサーを作れるように変更
Siv3D/OpenSiv3D pull request #1251
Opened 2024-07-29 09:50 UTC by Aikawa3311

新しくフォークし直して再度コミットしました。
以下前回のプルリクエストと同文です。

2D 物理演算で円形以外の形状のセンサーを作れるように変更を加えました。

`P2Rect` や `P2Triangle` などのコンストラクタの引数に `bool isSensor` を加えています。
`P2Body` や `P2World` などに `addRectSensor()` や `createRectSensor()` などのセンサーを作る関数を加えています。
`P2World::createCircle()` にオーバーロードが 2 つ存在しているので、それに合わせて `P2World::createCircleSensor()` も新たに 1 つオーバーロードを加えました。

次のコードで動作を確認しました。
https://gist.github.com/Aikawa3311/a8bc38cc4667f5d93b3378ef402df276

2024-07-29 09:54 UTC, Reputeless commented
ありがとうございます。確認します。

2024-08-07 15:22 UTC, Reputeless requested changes
関数内のエラーメッセージを 3 箇所修正してください。

2024-08-07 15:22 UTC, Reputeless commented on Siv3D/src/Siv3D/Physics2D/P2World.cpp
> +			throw Error{ U"P2World::createLineString(): bodyType must be either P2BodyType::Static or P2BodyType::Kinematic" };
エラーメッセージ内の関数名を `～Sensor()` に修正してください。

2024-08-07 15:22 UTC, Reputeless commented on Siv3D/src/Siv3D/Physics2D/P2World.cpp
> +			throw Error{ U"P2World::createClosedLineString(): bodyType must be either P2BodyType::Static or P2BodyType::Kinematic" };
エラーメッセージ内の関数名を `～Sensor()` に修正してください。

2024-08-07 15:22 UTC, Reputeless commented on Siv3D/src/Siv3D/Physics2D/P2World.cpp
> +			throw Error{ U"P2World::createLine(): bodyType must be either P2BodyType::Static or P2BodyType::Kinematic" };
エラーメッセージ内の関数名を `～Sensor()` に修正してください。

2024-08-07 15:23 UTC, Reputeless commented
上記以外は LGTM なので、修正完了次第 v0.6.16 へマージしたいと思います！

2024-08-08 07:34 UTC, Aikawa3311 commented
ありがとうございます。
先ほどエラーメッセージの内容を修正したものをコミットしてみました。
ご確認よろしくお願いします。

2024-08-08 07:53 UTC, Reputeless approved these changes

2024-08-08 07:54 UTC, merged

2024-08-08 07:54 UTC, Reputeless commented
Merged. Well done!