[Linux] TextInputのIME対応
Siv3D/OpenSiv3D pull request #627
Opened 2021-08-07 11:25 UTC by sthairno

- GLFWを一部改変し、XIMによる日本語入力に対応しました。
- 以下のLinux専用のAPIを実装しました。
  - IMEの有効/無効切り替え (`Platform::Linux::TextInput()`)
  - カーソル位置の取得 (`Platform::Linux::GetCursorIndex()`)
  - 編集中文字列のスタイル取得 (`Platform::Linux::GetEditingTextStyle()`)

2021-08-07 11:29 UTC, sthairno commented
検証するにあたって作成したテストコードです。

```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.6.0

void Main()
{
	Scene::SetBackground(ColorF{ 0.8, 0.9, 1.0 });
	const Font font{ 20 };

	bool enabled = true;
	TextEditState state;
	while (System::Update())
	{
		ClearPrint();

		SimpleGUI::TextBox(state, {10,10});

		auto cursor = Platform::Linux::TextInput::GetCursorIndex();
		auto& style = Platform::Linux::TextInput::GetEditingTextStyle();
		for(auto [idx, c] : Indexed(TextInput::GetEditingText()))
		{
			Print << U"{}, {:04b} {}"_fmt(c, static_cast<int32>(style[idx]), cursor == idx ? U"<-" : U"");
		}

		if(SimpleGUI::Button(enabled ? U"Disable" : U"Enable", {10, 50}))
		{
			if(enabled) {
				Platform::Linux::TextInput::DisableIME();
			} else {
				Platform::Linux::TextInput::EnableIME();
			}
			enabled = !enabled;
		}
	}
}
```

2021-08-13 02:36 UTC, Reputeless requested changes
レビュー、対応をお願いします。

2021-08-13 02:36 UTC, Reputeless commented on Siv3D/include/Siv3D/TextInput.hpp
> +		const Array<UnderlineStyle>& GetEditingTextStyle();
`[[nodiscard]]` が必要です。

2021-08-13 02:36 UTC, Reputeless commented on Siv3D/include/Siv3D/UnderlineStyle.hpp
> +	enum class UnderlineStyle
最小限の表現ができる符号なし整数型を enum-base にします。
今回は `: uint8` を。

2021-08-13 02:36 UTC, Reputeless commented on Siv3D/src/Siv3D-Platform/Linux/Siv3D/TextInput/CTextInput.cpp
> +	void CTextInput::enableIME(bool enabled)
`const bool enabled`

2021-08-21 14:20 UTC, merged

2021-08-21 14:21 UTC, Reputeless commented
Excellent work!