不要なコピーの回避
Siv3D/OpenSiv3D pull request #953
Opened 2023-02-10 18:26 UTC by Raclamusi

ムーブされるべき場面でコピーが行われるようなコードがあったので、ムーブされるように修正しました。

以下のようなコードを修正しました。

1. メンバ関数が返す左辺値参照で構築している

```c++
struct T
{
    T& foo()
    {
        // …
        return *this;
    }
    T fooed() const&
    {
        return T{ *this }.foo();  // copy! → `std::move` で囲む
    }
};
```

2. メンバ関数内でのメンバ関数呼び出しの際に `*this` をムーブしていない

```c++
struct T
{
    const T& foo() const&
    {
        // …
        return *this;
    }
    T foo() &&
    {
        // …
        return std::move(*this);
    }
    T bar() &&
    {
        return foo();  // copy! `foo() const&` が呼ばれる → `std::move(*this).foo()` のように呼び出す
    }
};
```

3. `std::move` を使っていない

```c++
struct T
{
    using value_type = /* … */;
    Array<value_type> m_data;

    value_type operator [](std::size_t index) &&
    {
        return std::move(m_data[index]);
    }
    value_type at(std::size_t index) &&
    {
        return m_data.at(index);  // copy! → `std::move` で囲む
    }
};
```

2023-02-15 11:12 UTC, Reputeless requested changes
パフォーマンス上重要な修正を指摘いただきありがとうございます。
いくつか変更が不要な点、合わせて直したい点もあるのでご確認ください。

2023-02-15 11:12 UTC, Reputeless commented on Siv3D/include/Siv3D/detail/String.ipp
> +		return std::move(m_string.at(offset));
配列的クラスの `at() &&`, `operator [](size_t) &&` メンバ関数は、次のような事故を防ぐ目的で用意しました。
- https://wandbox.org/permlink/6H39m2eEPxTbGIIT

`Circular` 同様、ムーブが不要なオブジェクト（ここでは `char32`）では `std::move()` は省略したいです。

`String::operator[]()(size_t) &&` で使われている `std::move()` も省略すべきですね。
https://github.com/Siv3D/OpenSiv3D/pull/953/files#diff-f521c0091c2cde3e02782b7a3bdffcc196d5a3f088779d0005a31623f68921d9R489

2023-02-15 11:12 UTC, Reputeless commented on Siv3D/include/Siv3D/detail/Wave.ipp
> +		return std::move(m_data.at(index));
`String::at()` のコメントと同理由で、不要です。
そして `Wave::operaotr[](size_t) &&` の `std::move()` も外しましょう。

2023-02-15 14:52 UTC, Raclamusi commented
ムーブが不要なオブジェクトについてのムーブは書き方を統一するぐらいの気持ちでつけていましたが、最適化なしのビルドのことを考えると確かに `std::move` をつけない方がいいですね。
修正します。

2023-02-16 06:06 UTC, merged

2023-02-16 06:06 UTC, Reputeless commented
Merged. Well done!